# Generated by Django 4.2.5 on 2023-10-13 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('kmdriven', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300, null=True)),
                ('phn', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
